<?php

/**
 * @file
 * Provides a conta entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function conta_entity_theme() {
  return [
    'conta_entity' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for conta templates.
 *
 * Default template: conta-entity.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the conta information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_conta_entity(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
