artistic_couvert.artistic_couvert.*:
  type: config_entity
  label: artistic-couvert
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string
